#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/5fd77d83-95dc-4f51-bd08-69a2a484f6d8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String detectedAnimal;
  String lastFeedTime;
  float foodLevel;
  CloudSchedule scheduleTime;
  bool autoFeed;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include <Servo.h>
#define TRIG_PIN D5
#define ECHO_PIN D6
const float MAX_DISTANCE = 70.0; // distance (cm) when container is empty
const float MIN_DISTANCE = 5.0;
int buzzerPin = 4;//D2
Servo Servo9;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  Servo9.attach(0);    //D3
  pinMode(5, INPUT);    //D1
  pinMode(buzzerPin, OUTPUT);
  digitalWrite(buzzerPin,LOW);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  float distance = getDistance();
  foodLevel = mapDistanceToPercentage(distance);

  Serial.print("Distance: ");
  Serial.print(distance);
  Serial.print(" cm | Food Level: ");
  Serial.print(foodLevel);
  Serial.println("%");

  delay(2000);

  
  if(scheduleTime.isActive()){
    digitalWrite(buzzerPin,LOW);
    if((digitalRead(5) == 0)) {
		Servo9.write(0);
        delay(2000);
	}
	else {
		Servo9.write(180);
	}
  }else{
    digitalWrite(buzzerPin,HIGH);
    Servo9.write(180);
  }
  

if (Serial.available()) {
    String msg = Serial.readStringUntil('\n');
    msg.trim();

    if (msg.length() > 0) {
      detectedAnimal = msg;  // update IoT Cloud variable
      Serial.println("Updated Cloud variable: " + detectedAnimal);
    }
  }
  
}




void onScheduleTimeChange()  {
  // Add your code here to act upon ScheduleTime change
}


void onAutoFeedChange()  {
  // Add your code here to act upon AutoFeed change
  if(autoFeed){
    Servo9.write(0);
    delay(2000);
  }else{
    Servo9.write(180);
  }
}

float getDistance() {
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  long duration = pulseIn(ECHO_PIN, HIGH);
  float distance = duration * 0.0343 / 2;
  return distance;
}

float mapDistanceToPercentage(float distance) {
  if (distance <= MIN_DISTANCE) return 100;
  if (distance >= MAX_DISTANCE) return 0;

  return 100 * (MAX_DISTANCE - distance) / (MAX_DISTANCE - MIN_DISTANCE);
}





/*
  Since DetectedAnimal is READ_WRITE variable, onDetectedAnimalChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDetectedAnimalChange()  {
  // Add your code here to act upon DetectedAnimal change
}
