// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b15abd84-1165-40bc-950c-b9c537021f76";

const char SSID[]               = "My network";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "WpNWYNk@fvaxk1AKzJ7AXPFff";    // Secret device password

void onDetectedAnimalChange();
void onScheduleTimeChange();
void onAutoFeedChange();

String detectedAnimal;
String lastFeedTime;
float foodLevel;
CloudSchedule scheduleTime;
bool autoFeed;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(detectedAnimal, READWRITE, ON_CHANGE, onDetectedAnimalChange);
  ArduinoCloud.addProperty(lastFeedTime, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(foodLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(scheduleTime, READWRITE, ON_CHANGE, onScheduleTimeChange);
  ArduinoCloud.addProperty(autoFeed, READWRITE, ON_CHANGE, onAutoFeedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
