// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b15abd84-1165-40bc-950c-b9c537021f76";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDetectedAnimalChange();
void onScheduleTimeChange();
void onAutoFeedChange();
void onAutoFeed2Change();

String detectedAnimal;
float foodLevel;
CloudSchedule scheduleTime;
bool autoFeed;
bool autoFeed2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(detectedAnimal, READWRITE, ON_CHANGE, onDetectedAnimalChange);
  ArduinoCloud.addProperty(foodLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(scheduleTime, READWRITE, ON_CHANGE, onScheduleTimeChange);
  ArduinoCloud.addProperty(autoFeed, READWRITE, ON_CHANGE, onAutoFeedChange);
  ArduinoCloud.addProperty(autoFeed2, READWRITE, ON_CHANGE, onAutoFeed2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
